General:
  storage_mode: 'tel_type'
  tel_type_list:
    - 'LST:LSTCam'
    - 'MST:FlashCam'
    - 'MST:NectarCam'
    - 'MST-SCT:SCTCam'
    - 'SST:DigiCam'
    - 'SST:ASTRICam'
    - 'SST:CHEC'

Image:
  img_mode: '1D'
  img_channels: 1
  include_timing: True
  img_scale_factors:
      'NectarCam': 1
  img_dtypes:
      'LSTCam': 'float32'
      'NectarCam': 'float32'
      'FlashCam': 'float32'
      'SCTCam': 'float32'
      'DigiCam': 'float32'
      'ASTRICam': 'float32'
      'CHEC': 'float32'
  img_dim_order: 'channels_last'

Preselection Cuts:
  ED_cuts_dict:
  cuts_dict:

Compression:
  comp_lib: 'lzo'
  comp_lvl: 1

Chunking:
  expected_tel_types: 10
  expected_tels: 300
  expected_events: 10000
  expected_images_per_event:
      'LST:LSTCam': 0.5
      'MST:NectarCam': 2.0
      'MST:FlashCam': 2.0
      'MST-SCT:SCTCam': 1.5
      'SST:DigiCam': 1.25
      'SST:ASTRICam': 1.25
      'SST:CHEC': 1.25
